Nested Product/Categories Pages
adobe/aem-core-cif-components pull request #461
Opened 2021-01-08 08:31 UTC by realgpp

## Description

With the PR it is possible to organize the structure of the product/categories pages even replicating the structure of the catalog present on Magento with nested hierarchical categories

## Related Issue

[Here](https://github.com/adobe/aem-core-cif-components/issues/446) the related discussion

## Motivation and Context

If the client want to customize the product/category pages heavily by creating many pages that differs each others it can lead to a messy and extremely long list of child pages under "products/product-page". By using a hierarchical tree the editors has ability to define the structure they prefer according to their needs. 

## How Has This Been Tested?

Has been tested by creating nested pages under product and category roots.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2021-01-12 10:21 UTC, herzog31 approved these changes
👍 
I pushed a copy of this PR to https://github.com/adobe/aem-core-cif-components/tree/pr/461 to run the ITs and they pass.

2021-01-12 10:48 UTC, cjelger requested changes
You should add a test in `UrlProviderImplTest` similar to what you did in `PageTypeRenderConditionServletTest` to make sure you cover your proposed change: right now, if you check the coverage computed by `codecov`, you never get into the code that returns the `grandChild`.

2021-01-12 10:50 UTC, cjelger commented
@realgpp Thx, you added the test at the same time I added my comment ;-)

2021-01-12 10:59 UTC, cjelger approved these changes

2021-01-26 11:22 UTC, alkim91 approved these changes

2021-02-01 10:35 UTC, merged