Replace import of miniaccount node
adobe/aem-core-cif-components pull request #471
Opened 2021-01-23 20:14 UTC by Tylopilus

The hard requirement used to be replaced in a earlier PR

## Description
Replace import of miniaccount-component with direct mapping-div

## Related Issue

Solves https://github.com/adobe/aem-core-cif-components/issues/470

## Motivation and Context

The hard requirement leads to an unrenderable page/template if the navigation component gets dragged on a page/template. Only adding a manual node in code/crx solves this issue. But since its just a single div that gets replaced the requirement of the miniaccount-component is unnecessary. 
## How Has This Been Tested?

AEM as a Cloud Service SDK - latest

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-02-24 10:07 UTC, dplaton requested changes

2021-02-24 10:07 UTC, dplaton commented on ui.apps/src/main/content/jcr_root/apps/core/cif/components/structure/navigation/v1/navigation/navigation.html
> +    <div id="miniaccount"></div>
A div with this id is already added by the `miniaccount` component - https://github.com/adobe/aem-core-cif-components/blob/9ad38db585e48c320eb031c4dcfbfbc44737d9b6/ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/miniaccount/v1/miniaccount/miniaccount.html#L14

You should keep the resource inclusion approach but check for the resource first.

2021-04-19 08:14 UTC, LSantha commented
This will be fixed here: https://github.com/adobe/aem-core-cif-components/pull/543/files#diff-6f40073465095d59939eabdc6e701c11ebfa183db84a31d16e32004624b4afd2R25-R27

2021-04-22 13:28 UTC, LSantha commented
Closing this PR since it was fixed with https://github.com/adobe/aem-core-cif-components/pull/543/files#diff-6f40073465095d59939eabdc6e701c11ebfa183db84a31d16e32004624b4afd2R25-R27.

2021-04-22 13:28 UTC, closed without merging