CIF-1974 - Core Components: navigation - use UID for category queries
adobe/aem-core-cif-components pull request #528
Opened 2021-03-29 19:18 UTC by LSantha

* added category UID support for navigation component

## Related Issue

CIF-1974

## Motivation and Context

Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

2021-04-06 14:11 UTC, dplaton approved these changes

2021-04-08 11:00 UTC, laurentiumagureanu requested changes

2021-04-08 11:09 UTC, herzog31 commented on bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
> +    private static final Function<CategoryTreeQuery, CategoryTreeQuery> CATEGORIES_QUERY = q -> q.id().uid().name().urlPath().position();
How does this break backwards compatibility? Next version of CIF components will require 2.4.2 and you can always query _for_ the UID. The only place where we have to be careful is when we query _by_ UID.

2021-04-08 11:16 UTC, herzog31 approved these changes

2021-04-08 12:49 UTC, LSantha commented on bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/navigation/GraphQLCategoryProvider.java
> +    private static final Function<CategoryTreeQuery, CategoryTreeQuery> CATEGORIES_QUERY = q -> q.id().uid().name().urlPath().position();
@laurentiumagureanu , could you please clarify? I also think that in Magento 2.4.2 the category uid will be always available.

2021-04-13 11:32 UTC, merged