CIF-2144 - Create a React project with a Recommendation component
adobe/aem-core-cif-components pull request #605
Opened 2021-06-30 10:14 UTC by herzog31

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2021-07-08 09:12 UTC, dplaton approved these changes
I had only minor comments, so 👍  We should still think of a better name, though...

2021-07-14 07:40 UTC, laurentiumagureanu approved these changes

2021-07-14 08:19 UTC, Buuhuu requested changes

2021-07-14 08:19 UTC, Buuhuu commented on extensions/product-recs/react-components/src/components/ProductRecsGallery/ProductCard.js
> +        const isRange = !!(Math.round(minimum.final * 100) != Math.round(maximum.final * 100));
Is the `!!` necessary here? the `!=` comparison should already result in a `boolean`. You may want to use a strict comparison event `!==`

2021-07-14 08:19 UTC, Buuhuu commented on react-components/src/utils/createProductPageUrl.js
> +    url.pathname = `${path}.cifproductredirect${extension}/product/${sku}`;
The `/product/` should not be included anymore. The pattern is `{{page}}.cifproductredirect.html/{{sku}}`.

2021-07-14 08:19 UTC, Buuhuu commented on react-components/src/utils/createProductPageUrl.js
> +    const extension = pathname.substr(pathname.lastIndexOf('.'));
We should fix the extension to `html` as this is also how the servlet is registered.

2021-07-14 10:21 UTC, Buuhuu approved these changes

2021-07-21 15:36 UTC, merged